# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Generate the gRPC code from the .proto file
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. greeter.proto

# Streamlit runs on port 8501 by default
EXPOSE 8501

# Define the command to run your Streamlit app
# --server.port is crucial for Cloud Run
CMD ["streamlit", "run", "streamlit_client_gcp.py", "--server.port=8501", "--server.address=0.0.0.0"]
